# Generated by Django 2.1.3 on 2018-11-24 18:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=50, verbose_name='REITTI')),
                ('name', models.CharField(max_length=50, verbose_name='NIMI')),
                ('transport_type', models.IntegerField(verbose_name='VERKKO')),
                ('tariff_area', models.CharField(max_length=50, verbose_name='TARIFFIALU')),
                ('mpoly', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
