# Generated by Django 2.1.3 on 2018-11-24 18:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20181124_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspooRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kokotun', models.CharField(max_length=254)),
                ('kunta', models.CharField(max_length=254)),
                ('suur', models.CharField(max_length=254)),
                ('tila', models.CharField(max_length=254)),
                ('pien', models.CharField(max_length=254)),
                ('nimi', models.CharField(max_length=254)),
                ('nimi_iso', models.CharField(max_length=254)),
                ('mtryhm', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
