# Generated by Django 2.1.3 on 2018-11-24 19:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20181124_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspooSmallRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kokotun', models.CharField(max_length=254)),
                ('kunta_name', models.CharField(max_length=254, verbose_name='kunta')),
                ('greater', models.CharField(max_length=254, verbose_name='suur')),
                ('space', models.CharField(max_length=254, verbose_name='tila')),
                ('smaller', models.CharField(max_length=254, verbose_name='pien')),
                ('name', models.CharField(max_length=254, verbose_name='nimi')),
                ('name_larger', models.CharField(max_length=254, verbose_name='nimi_iso')),
                ('some_group', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='EspooRegions',
        ),
    ]
